"""Create initial tables

Revision ID: 0be2b47c48b0
Revises: 
Create Date: 2025-11-16 15:37:58.175402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0be2b47c48b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='포트폴리오 이름'),
    sa.Column('description', sa.Text(), nullable=True, comment='설명'),
    sa.Column('target_return', sa.Numeric(precision=5, scale=2), nullable=True, comment='목표 수익률 (%)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='수정일시'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_id'), 'portfolios', ['id'], unique=False)
    op.create_index(op.f('ix_portfolios_name'), 'portfolios', ['name'], unique=False)
    op.create_table('etf_holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False, comment='포트폴리오 ID'),
    sa.Column('ticker', sa.String(length=20), nullable=False, comment='ETF 티커 (예: SPY, QQQ)'),
    sa.Column('name', sa.String(length=200), nullable=True, comment='ETF 이름'),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False, comment='보유 수량'),
    sa.Column('average_price', sa.Numeric(precision=20, scale=2), nullable=False, comment='평균 매수가 (USD)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='수정일시'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etf_holdings_id'), 'etf_holdings', ['id'], unique=False)
    op.create_index(op.f('ix_etf_holdings_portfolio_id'), 'etf_holdings', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_etf_holdings_ticker'), 'etf_holdings', ['ticker'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False, comment='포트폴리오 ID'),
    sa.Column('ticker', sa.String(length=20), nullable=False, comment='ETF 티커 (예: SPY, QQQ)'),
    sa.Column('transaction_type', sa.Enum('BUY', 'SELL', name='transactiontype'), nullable=False, comment='거래 유형 (buy/sell)'),
    sa.Column('transaction_date', sa.Date(), nullable=False, comment='거래일'),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False, comment='거래 수량'),
    sa.Column('price', sa.Numeric(precision=20, scale=2), nullable=False, comment='거래 단가 (USD)'),
    sa.Column('total_amount', sa.Numeric(precision=20, scale=2), nullable=False, comment='총 거래금액 (USD)'),
    sa.Column('fee', sa.Numeric(precision=20, scale=2), nullable=True, comment='수수료 (USD)'),
    sa.Column('note', sa.String(length=500), nullable=True, comment='메모'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성일시'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_portfolio_id'), 'transactions', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_transactions_ticker'), 'transactions', ['ticker'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_ticker'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_portfolio_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_etf_holdings_ticker'), table_name='etf_holdings')
    op.drop_index(op.f('ix_etf_holdings_portfolio_id'), table_name='etf_holdings')
    op.drop_index(op.f('ix_etf_holdings_id'), table_name='etf_holdings')
    op.drop_table('etf_holdings')
    op.drop_index(op.f('ix_portfolios_name'), table_name='portfolios')
    op.drop_index(op.f('ix_portfolios_id'), table_name='portfolios')
    op.drop_table('portfolios')
    # ### end Alembic commands ###
